apiVersion: v1
kind: ReplicationController
metadata:
  name: tech-conf-2017
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tech-conf-2017
    spec:
      restartPolicy: Always
      volumes:
      - name: nginx-secret
        secret:
          secretName: nginx-secret
      - name: nginx-conf
        configMap:
          name: nginx-conf

      containers:

      - name: shl-bikeride-nginx
        image: eu.gcr.io/tech-conf-2017/super-duper-app:1
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/tls-certs
            name: nginx-secret
          - mountPath: /etc/nginx/conf.d/default.conf
            name: nginx-conf

---

apiVersion: v1
kind: Service
metadata:
  name: tech-conf-2017
  labels:
    app: tech-conf-2017
    veg: potato
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: tech-conf-2017
